version: '3.8'
services:
  api:
    container_name: cloudwatcher
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    image: cloudwatcher:latest
    ports:
      - "3000:3000"
    networks:
      - app
    depends_on:
      - postgres
  postgres:
    container_name: realo-postgres
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    networks:
      - app
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
    driver: local
networks:
  app:
    driver: bridge