name: codecov.io
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  upload:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm run ci
      - name: Run tests and generate code coverage report
        run: npm run test:cov
      - name: Upload code coverage report to codecov.io
        run: npx codecov -t ${{ secrets.CODECOV_TOKEN }}
