name: docker
on:
  push:
    branches:
      - master
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
        node: [18.16.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: npm run ci
      - name: Docker Push
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: abialiauski/cloudwatcher
          tags: 0.0.$GITHUB_RUN_NUMBER, latest
          dockerfile: Dockerfile
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}